"""add_v2_tables

Revision ID: 910bd1947b60
Revises: 
Create Date: 2026-02-13 23:44:20.784227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '910bd1947b60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_category'), 'agent_memory', ['category'], unique=False)
    op.create_index(op.f('ix_agent_memory_id'), 'agent_memory', ['id'], unique=False)
    # pgvector: add embedding column + indexes (not auto-detected by Alembic)
    op.execute("ALTER TABLE agent_memory ADD COLUMN IF NOT EXISTS embedding vector(1536)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_memory_embedding ON agent_memory USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_memory_fts ON agent_memory USING gin (to_tsvector('english', content))")
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_log', ['actor', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=200), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_sender', 'conversations', ['sender_id', 'created_at'], unique=False)
    op.create_index('idx_conversations_session', 'conversations', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_usage_date', 'llm_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_usage_id'), 'llm_usage', ['id'], unique=False)
    op.create_table('skill_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_skill_runs_name', 'skill_runs', ['skill_name', 'started_at'], unique=False)
    op.create_index(op.f('ix_skill_runs_id'), 'skill_runs', ['id'], unique=False)
    op.create_table('system_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_knowledge_id'), 'system_knowledge', ['id'], unique=False)
    op.create_index('uq_system_knowledge_domain_key', 'system_knowledge', ['domain', 'key'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('started_by', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('resume_token', sa.Text(), nullable=True),
    sa.Column('input_args', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_status', 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_id'), 'workflow_runs', ['id'], unique=False)
    op.add_column('alerts', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('commands', sa.Column('user_id', sa.String(length=100), nullable=True))
    op.add_column('commands', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('commands', sa.Column('thinking', sa.Text(), nullable=True))
    op.add_column('commands', sa.Column('tools_used', sa.JSON(), nullable=True))
    op.alter_column('commands', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('commands', 'context',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('commands', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('device_reports', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('device_reports', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('device_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('logs', sa.Column('details', sa.JSON(), nullable=True))
    op.alter_column('logs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('logs', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('logs', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logs', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('logs', 'details')
    op.alter_column('device_reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('device_reports', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('device_reports', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('commands', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('commands', 'context',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('commands', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('commands', 'tools_used')
    op.drop_column('commands', 'thinking')
    op.drop_column('commands', 'channel')
    op.drop_column('commands', 'user_id')
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'acknowledged')
    op.drop_column('alerts', 'title')
    op.drop_column('alerts', 'source')
    op.drop_index(op.f('ix_workflow_runs_id'), table_name='workflow_runs')
    op.drop_index('idx_workflow_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('uq_system_knowledge_domain_key', table_name='system_knowledge')
    op.drop_index(op.f('ix_system_knowledge_id'), table_name='system_knowledge')
    op.drop_table('system_knowledge')
    op.drop_index(op.f('ix_skill_runs_id'), table_name='skill_runs')
    op.drop_index('idx_skill_runs_name', table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_index(op.f('ix_llm_usage_id'), table_name='llm_usage')
    op.drop_index('idx_llm_usage_date', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('idx_conversations_session', table_name='conversations')
    op.drop_index('idx_conversations_sender', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_memory_id'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_category'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
